import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LayoutNav from "@/components/LayoutNav";
import Container from "@/components/Container";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Instagram } from "lucide-react";
import { FaWhatsapp } from "react-icons/fa6";
import FinalPresentation from "@/components/FinalPresentation";
import Script from "next/script";
import WppClickToChat from "@/components/WppClickToChat";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dra. Danielle Moraes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Script id="google-tag-manager" strategy="afterInteractive">
          {`(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
          new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
          j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
          'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
          })(window,document,'script','dataLayer','GTM-WM26RCKM');`}
        </Script>
        <div
          dangerouslySetInnerHTML={{
            __html: `<noscript>
          <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WM26RCKM"
          height="0" width="0" style="display:none;visibility:hidden"></iframe>
        </noscript>`,
          }}
        />

        <LayoutNav />

        <main className="overflow-x-hidden">{children}</main>

        <FinalPresentation />

        <footer className="bg-primary900 text-background">
          <Container className="grid grid-cols-2 md:grid-cols-4 gap-8 py-8">
            <div className="flex flex-col items-start font-custom font-light text-3xl italic text-background">
              <p>Dra.</p>
              <p>Danielle</p>
              <p>Moraes</p>
            </div>
            <div className="">
              <p className="text-lg">Endereço</p>
              <p>
                Rua Luis Antônio de Andrade Vieira, 216, Boqueirão – Praia
                Grande SP (sala 512)
              </p>
            </div>
            <div className="">
              <p className="text-lg">Contato</p>
              <p>WhatsApp: (13) 99805-1611</p>
            </div>
            <div className="">
              <p className="text-lg">Acompanhe</p>
              <span className="flex gap-2">
                <Button variant={"ghost"} className="rounded-full p-2">
                  <Link
                    href="https://www.instagram.com/dradanimoraess/"
                    target="_blank"
                  >
                    <Instagram />
                  </Link>
                </Button>
                <Button variant={"ghost"} className="rounded-full p-2">
                  <Link href="https://wa.me/13998051611" target="_blank">
                    <FaWhatsapp size={24} />
                  </Link>
                </Button>
              </span>
            </div>
          </Container>
        </footer>

        <WppClickToChat />
      </body>
    </html>
  );
}
