import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LayoutNav from "@/components/LayoutNav";
import Container from "@/components/Container";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Instagram } from "lucide-react";
import { FaWhatsapp } from "react-icons/fa6";
import FinalPresentation from "@/components/FinalPresentation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dra. Dani Moraes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutNav />

        <main className="overflow-x-hidden">{children}</main>

        <FinalPresentation />

        <footer className="bg-stone-800 text-background">
          <Container className="grid grid-cols-2 md:grid-cols-4 gap-8 py-8">
            <div className="flex flex-col items-start font-custom font-light text-3xl italic text-stone-500">
              <p>Dra.</p>
              <p>Dani</p>
              <p>Moraes</p>
            </div>
            <div className="">
              <p className="text-lg">Endereço</p>
              <p>
                Rua Luis Antônio de Andrade Vieira, 216, Boqueirão – Praia
                Grande SP (sala 512)
              </p>
            </div>
            <div className="">
              <p className="text-lg">Contato</p>
              <p>WhatsApp: (13) 99805-1611</p>
            </div>
            <div className="">
              <p className="text-lg">Acompanhe</p>
              <span className="flex gap-2">
                <Button variant={"ghost"} className="rounded-full p-2">
                  <Link
                    href="https://www.instagram.com/dradanimoraess/"
                    target="_blank"
                  >
                    <Instagram />
                  </Link>
                </Button>
                <Button variant={"ghost"} className="rounded-full p-2">
                  <Link href="https://wa.me/13998051611" target="_blank">
                    <FaWhatsapp size={24} />
                  </Link>
                </Button>
              </span>
            </div>
          </Container>
        </footer>
      </body>
    </html>
  );
}
