import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LayoutNav from "@/components/LayoutNav";
import Container from "@/components/Container";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Instagram } from "lucide-react";
import FinalPresentation from "@/components/FinalPresentation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dra. Dani Moraes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutNav />

        <main className="overflow-x-hidden">{children}</main>

        <FinalPresentation />

        <footer className="bg-main text-background">
          <Container className="grid grid-cols-2 md:grid-cols-4 gap-8 py-8">
            <div className="flex flex-col items-start font-custom font-thin text-3xl italic text-yellow-200/60">
              <p>Dra.</p>
              <p>Dani</p>
              <p>Moraes</p>
            </div>
            <div className="">
              <p className="text-lg">Endereço</p>
              <p>Rua Canadá, 215, Jd. América – São Paulo SP</p>
            </div>
            <div className="">
              <p className="text-lg">Contato</p>
              <p>WhatsApp: (11) 95776-1003</p>
            </div>
            <div className="">
              <p className="text-lg">Acompanhe</p>
              <Button variant={"ghost"} className="rounded-full p-2 text-main2">
                <Link
                  href="https://www.instagram.com/dradanimoraess/"
                  target="_blank"
                >
                  <Instagram />
                </Link>
              </Button>
            </div>
          </Container>
        </footer>
      </body>
    </html>
  );
}
